file1:
  url: "http://speedtest.tele2.net/1MB.zip"
  dest: "./file"
file2:
  url: "ftp://speedtest.tele2.net/1KB.zip"
  dest: "./file"
file3:
  url: "http://google.com/blah"
  dest: "./file"
file4:
  dest: "./file"
file5:
  url: "http://speedtest.tele2.net/1MB.zip"
file6:
  url: "ftps://XXX:XXXX@localhost/path"
  dest: "./file"
file7:
  url: "sftp://XXXX:XXXX@localhost/path"
  dest: "./file"
file8:
  url: "sftp://XXXX@localhost/path"
  dest: "./file"
  key_filename: "/.ssh/pkey"
  passphrase: "pass"